### PR TITLE
Added bower.json

### PR DESCRIPTION
**Pull request by MaffooBristol**

### CODE REVIEW

**Comment by lukehorvat** [comment]
Would be nice to be able to access versions of SoundManager2 via the Bower registry.

**Comment by MaffooBristol** [comment]
@lukehorvat Yep, but they'll have to merge the PR for that first, but releases seem like a very uncommon thing.

You can still use bower to install it from Git as a temporary solution, though. At the moment I'm using my own fork and have this in my bower.json file:

`"SoundManager2": "git@github.com:Soniflow/SoundManager2.git"`

**Comment by scottschiller** [comment]
Thanks for the PR; sorry I've been bad about updates here, I have just returned from vacation and have been busy otherwise with professional work.

SM2 is a mature project (it started in the early 2000s) and releases are less-frequent than they used to be - I typically aim for once a quarter unless there are pressing issues. Another update is due soon, so I'll revisit this with the next round.

**Comment by ChALkeR** [comment]
Shouldn't you ignore `doc` and `demo` folders?
`demo` is 10.5 MiB, `doc` is 1.4 MiB,  all the rest is 0.6 MiB.
`demo` and `doc` are not really needed inside bower_components.

Also, idk if the`src` folder (containing flash sources) is needed.

**Comment by MaffooBristol** [comment]
@scottschiller No worries, completely understandable! And thanks for providing this module in the first place, I was dreading having to write the audio player code for my project as I hadn't heard of SM2 before now, but it's been a real godsend, so many thanks. And bower is very important in my case as my application architecture relies heavily on it, so it's a useful addition with very little effort :smile: 

And yes, @ChALkeR , you're right. I was a bit lax with the ignore folders; I'll amend the PR asap. Ta!

**Pull request merged**
