### PR TITLE
Can we enable the issues for that project?!

### PR DESCRIPTION
**Pull request by lipis**
Maybe I missed a lot of things.. but why not having the issues enabled? Even if you the core team doesn't have much time.. people could file issues and others could do PRs...

### CODE REVIEW

**Comment by scottschiller** [comment]
You're not alone in this request - I plan to bring this back with the next release.
https://github.com/scottschiller/SoundManager2/pull/27

I've traditionally done support via Get Satisfaction since 2008-ish, but understand most devs prefer GH since it's convenient + code-centric.

I'm also moving the SM2 homepage to a new host and a bunch of other things, to stay tuned. :)

**Comment by lipis** [comment]
Opening the issue tab is not a big deal.. so I don't see a reason why waiting with it?

**Comment by tchoulihan** [comment]
@scottschiller 
I found a bug with bar-ui, where can I submit that? If you'd open up bugs here that'd be a huge help.

**Comment by lipis** [comment]
Actually the issues are enabled.. https://github.com/scottschiller/SoundManager2/issues

**Comment by scottschiller** [comment]
Sorry, have re-enabled these finally. :grin: For years I've used GetSatisfaction for issues / support / requests, but I know these are useful as well.

**Comment by tchoulihan** [comment]
@scottschiller Thanks a ton good sir!

**Pull request closed without merging**
