### PR TITLE
Not a patch, but an issue. Issues tab was deleted.

### PR DESCRIPTION
**Pull request by dandv**
I'm aware of GetSatisfaction, and left a comment there on opening GitHub issues a well - https://getsatisfaction.com/schillmania/topics/broken_link_to_gzip_in_the_docs

### CODE REVIEW

**Comment by lucianmoldovan** [comment]
+1

**Comment by dandv** [comment]
De acord cu tine, Luciane

**Comment by honkskillet** [comment]
++
Also, needs a bower.json file.

**Comment by scottschiller** [comment]
Closing this one out, I have since re-enabled the issues tab. Apologies!

**Pull request closed without merging**
