### PR TITLE
Added support for component.

### PR DESCRIPTION
**Pull request by briandeheus**

### CODE REVIEW

**Comment by scottschiller** [comment]
I'm going to award myself the worst-yet follow-up on a PR, with apologies. ;) I missed getting this in for the last release of SM2 (09/2014), and am working this in for the next one, planned for next weekend.
I've merged this in on the current dev branch. 
https://github.com/scottschiller/SoundManager2/commit/17581181a6ce7594dded88fce9c030d5128ef7dc

I like the idea of debug-enabled vs. no-debug-jsmin versions. Is there One Weird Trick™ to declaring multiple versions (like dev/debug vs. production/no-debug) in component.json files that I'm not aware of?

**Comment by scottschiller** [comment]
It appears procrastination may have paid off in this case, in fact - is component no longer relevant?
http://www.jongleberry.com/the-future-of-component.html

**Comment by bjornstar** [comment]
As far as I can tell there's no implicit support for multiple versions within the same component.json file. The only thing I can suggest would be to create a different tag for each version as part of your build process. 

Unfortunately, I am no longer working on the projects that used SoundManager2 with Component. v1 was a bit of a mess so we ended up forking Component v0.18. 

It doesn't hurt to have the option available for people to use. I always find it nicer if I don't have to fork a library to use it in my build process.

**Comment by scottschiller** [comment]
Thanks for the note. As you say, likely little harm in having the option available.

**Comment by shennan** [comment]
It certainly feels like it now. But I'm not sure whether it has simply been
replaced by Duo.

http://duojs.org

I will say that I no longer use it and instead use my Browserify coupled
with some custom build scripts. It was very useful at one point, though.

**Pull request merged**
