### PR TITLE
throw error when cannot play using html5 player

### PR DESCRIPTION
**Pull request by tmutzafi**
Hello

Today there is no error thrown when you choose to play with html5 and this html audio throws and error.
I added code that throws onError on html5 error

in this case in my code I destruct the sm player and restart it with new setup setting of preferFlash true

example for an audio file that meets this requirement (doesn't works with html5 but works with flash)

http://storage.googleapis.com/static.wixstatic.com/mp3/578534_38932fe08397477f77ac90992f3f8213.mp3

it doesn't work with HTML5 since the file content-type is : audio/mpeg

### CODE REVIEW

**Comment by scottschiller** [comment]
Thank-you for the PR!

However, rebooting SM2 because of an error while attempting to load one file seems like a pretty drastic approach, one I would not recommend. There is also a chance you could get stuck in a reboot loop, since an increasing number of users do not have Flash installed (or, it may be blocked.)

SM2 is used in many places online, and sometimes a sound may fail to load due to a 404 (e.g., playing MP3 URLs from search results or other MP3-type search engines.)

With regards to your PR, error handling is actually in the API in terms of load failure. However, I have not done a good job of exposing it, i.e., an `onerror` callback in sound options .More on that below!

Re: your case: Recall that SM2 tries for HTML5 by default - so even if you _do_ say `preferFlash: true`, if SM2 reboots and can't load Flash (but it sees that HTML5 support is present), it will go with HTML5 so that it can at least offer HTML5 support.

This seems ultimately like an issue with the way this file is being served. If anything, I would file a bug with Google, or Wix, or whomever hosts that content to get the MIME response updated if you believe that is the crux of the issue.

If you think you will be often attempting to play files via the problematic domain given, I'd try starting SM2 with `preferFlash: true` right off the bat (e.g., `soundManager.setup({ preferFlash: true });`, and then you don't have to detect failure and attempt to reboot if playback fails.

Also! I need to improve this, but SM2 also currently indicates if a sound file fails to load. The method is not obvious, but the `onload` callback for a sound object has a boolean indicating load success. Due to some legacy Flash stuff, I think what I do internally here is check for a duration on the sound object to confirm that "something" loaded. :smile: 

e.g.
```mySound.play({
  onload: function(ok) {
    if (!ok) {
      // 404, MIME issue, ???
    }
  }
});```

Documentation needs updating on this as well, apologies - but the gist of it still applies.
http://www.schillmania.com/projects/soundmanager2/doc/#smsound-onload

I also need to add an explicit sound `onerror` event handler to address the above, something I keep forgetting about.

Thanks for the reminder!

**Comment by scottschiller** [comment]
Ack! You know what? Server responses actually look reasonable. I thought maybe the MIME might matter, but now I'm not sure. `audio/mpeg` should suffice for most HTML5 clients.

If you download the file and then drop the file right into Chrome from the desktop etc., it also fails to play. So it's likely something about that file that Chrome doesn't like; it's having trouble decoding the audio file. I'd try a few other MP3s like that one, and see if there's a pattern. It _might_ be something to do with the inline image art, etc., and related metadata causing problems for Chrome's media playback.

Dropping the same file here into Safari, unsurprisingly, seems to be OK.

If you find a pattern with a whole bunch of MP3s of a given type (i.e., from iTunes, Apple Store or what have you), it may be worth filing a bug on the Chromium project if you think a large number of MP3 files may simply fail to play in their browser.

**Comment by tmutzafi** [comment]
Hi

Thanks for the quick response..
You are right the reseting SM object just for one file is not that good. I used preferFlash true till now, in the latest chrome version (chrome 45) they have bug with flash + css animation (transform) and thats why i have to use HTML5 first (i saw they fixed it on canary already but we need a temp fix till than)

I checked what you said on the onLoad event with false and its works fine so i used that instead of what i sent to you 

Thanks

Tal

**Comment by scottschiller** [comment]
I'm not sure I follow the Chrome 45 Flash / CSS transform bug (is that related to audio at all?), but OK!

FWIW, I'm working on adding a proper "onerror" for the next release.
https://github.com/scottschiller/SoundManager2/commit/ebbebc6eb563488c2ea92447329cf9d8a7e247e1

**Pull request closed without merging**
