### PR TITLE
Add to set the title element for the media information shown in iOS.

### PR DESCRIPTION
**Pull request by elton2048**
This is a PR for the issue #180. As I also face the issue I decide to fix it by myself. It simply adds the title attribute if the related attribute exists in createSound method. Otherwise it will just use the default options with no title is set.

### CODE REVIEW

**Comment by scottschiller** [comment]
Ha, I completely missed this! 🙆‍♂️ Thanks.
Thumbnail would be handy also, if supported.
https://github.com/scottschiller/SoundManager2/issues/180#issuecomment-336660364

**Comment by elton2048** [comment]
I've googled the issue. Unfortunately there is no parameter which can control the thumbnail. It seems to be an issue for the iOS does not have corresponding interface for the browser kernel.

**Comment by eyes8570** [comment]
http://www.facebook.com/profile.php?id=100025554070482

**Comment by eyes8570** [comment]
14061

**Review by scottschiller — APPROVED** [review]
Getting to this PR, finally; thanks. Will work this into the next release.

**Pull request merged**
