### PR TITLE
Manually set useGlobalHTML5Audio to true with forceUseGlobalHTML5Audio option

### PR DESCRIPTION
**Pull request by itsjoesullivan**
Part of @snadn's pending [pull request](https://github.com/scottschiller/SoundManager2/pull/52) identifies an issue we're dealing with--Safari won't create new `<audio>` tags when the tab is backgrounded. There's already the internal `useGlobalHTML5Audio` flag, which gets switched on for iDevices, to re-use the initial audio tag. Modifying @snadn's code, this PR creates a `forceUseGlobalHTML5Audio` option which will manually switch on `useGlobalHTML5Audio`. This lets us fix our safari background-tab issue when setting up soundManager:

```javascript
soundManager.setup({
  forceUseGlobalHTML5Audio: true
});
```

### CODE REVIEW

**Comment by scottschiller** [comment]
Looks reasonable, thanks. :+1: Regrettable that desktop Safari does this, I might add.

**Comment by jasongrishkoff** [comment]
Could this be related to the issue identified in this thread?  Still haven't solved it on my side.
https://getsatisfaction.com/schillmania/topics/is_there_any_way_to_avoid_the_background_tab_issue_in_safari

**Comment by scottschiller** [comment]
I suspect it is, yes. Still annoying that Safari does this sort of stuff.
Sorry for the two-months-late follow-up here, completely missed your note. :D

**Comment by jasongrishkoff** [comment]
All good, thanks for getting back!  Can I just adjust the library to add the lines in this modified file, or does that forceUseGlobalHTML5Audio need to be declared somewhere else?

**Comment by scottschiller** [comment]
I merged this PR in March, but I haven't pushed a new release of SM2 (yet) including the feature - it's still on the dev branch. I'm reviewing and plan to push a release next weekend.

In the meantime, here's the commit where I worked this stuff in.
https://github.com/scottschiller/SoundManager2/commit/2a27d255c443bc14f6a6a88fd5c1d521ae6bb290

**Pull request merged**
